#!/bin/bash
echo "========================================="
echo "  ◈ AI SCANNER // NEXUS-OS v3.0"
echo "========================================="
echo "  Starting server..."
echo "========================================="
echo "  Access from another device on same WiFi:"
echo "  Open http://<YOUR_IP>:8000 on your phone"
echo "  Find YOUR_IP in Wireless > PHONE tab"
echo "========================================="
echo "  For public access:"
echo "  Install ngrok (free): https://ngrok.com"
echo "  Then run: ngrok http 8000"
echo "========================================="
gunicorn --bind=0.0.0.0:8000 --workers=2 --timeout=120 src.web_app:app
